### ISSUE TITLE
Pilot sometimes cannot be rescued

### ISSUE THREAD

**Issue by amanuense** [amanuense/DUWS-R#5]
I believe the issue might be that the rescue trigger area might be different than the HQ position, add a debug mode marker (area) to identify where the pilot should be rescued.

**Comment by CaiusAjiz** [comment]
@amanuense and I have spoken at length about this one outside of github and he's given me a number of good suggestions.

I'll begin with the debug marker to verify where the pilot's looking to get back to and go from there. Will branch off shortly to begin bug-hunting.

**Comment by CaiusAjiz** [comment]
I've added debug markers for both Pilot location inside of the collection zone and the area to take him back to (As part of branch "Bugfixing-Pilot-Rescue"). It's definitely taking the pilot back to the main base, with no deviation.

@amanuense As this issue has proven difficult for the pair of us to recreate, I'll expand out the distance for the pilot to the base from <50 to <=100 and we'll try that.

Thoughts?

**Comment by amanuense** [comment]
let's leave it to <100
same thing for steal truck mission.

Oscar

**Comment by CaiusAjiz** [comment]
Closing off issue as it's addressed in merge 23

**Comment by amanuense** [comment]
just a note, if you mention the issue on the commit message or on the pull
request the issue will close itself :)

Oscar
