### ISSUE TITLE
Add stock revive system configuration to params.hpp

### ISSUE THREAD

**Issue by amanuense** [amanuense/DUWS-R#7]
about a year ago I removed that configuration since it was crashing my linux server, issue should be fixed now.

don't have a linux server anymore need to get someone to test this

**Comment by CaiusAjiz** [comment]
I can build a Linux VM to help test this. I actually moved from Debian -> Windows server 2016 due to a different issue with Linux but can build a new box. Let me know when you want this server available and I'll start on it nearer the time.

**Comment by amanuense** [comment]
Whenever you have time.

**Comment by amanuense** [comment]
parameters are already added to params.hpp
